import type { Capability, RunLog } from '@/types';

export const capabilities: Capability[] = [
  {
    capabilityId: 'read_member_savings_balance',
    name: 'read_member_savings_balance',
    version: 3,
    goal: 'Member lookup, then read primary share balance',
    status: 'draft',
    inputs: [
      {
        name: 'memberNumber',
        valueType: 'string',
        required: true,
        description: 'Institution-issued member number. Validated before the browser is opened.',
      },
    ],
    outputs: [
      { name: 'savingsBalance', valueType: 'number', required: true },
      { name: 'shareAccountNumber', valueType: 'string', required: true },
      { name: 'asOf', valueType: 'date', required: true },
    ],
    steps: [
      {
        stepId: 'navigate-to-login',
        action: { actionType: 'navigate', url: 'http://127.0.0.1:4000/login' },
        waitFor: { waitUntil: 'pageLoad' },
      },
      {
        stepId: 'fill-member-number',
        action: {
          actionType: 'fill',
          target: [{ strategy: 'role', role: 'textbox', accessibleName: 'Member Number' }],
          value: '{{memberNumber}}',
        },
      },
      {
        stepId: 'click-search',
        action: {
          actionType: 'click',
          target: [{ strategy: 'role', role: 'button', accessibleName: 'Search' }],
        },
        waitFor: { waitUntil: 'pageLoad' },
      },
    ],
    checkpoints: [
      {
        checkpointId: 'on-detail-page',
        afterStepId: 'click-search',
        allOf: [
          { assert: 'text_present', text: 'SHARE SUMMARY' },
          { assert: 'url_matches', pattern: '/members/detail' },
        ],
      },
    ],
    extractions: [],
    businessOutcomes: [
      {
        code: 'member_not_found',
        message: 'No member matched the supplied number',
        condition: { when: 'checkpoint_failed', checkpointId: 'on-detail-page' },
      },
    ],
  },
  {
    capabilityId: 'verify_member_address',
    name: 'verify_member_address',
    version: 5,
    goal: 'Read mailing address of record for KYC checks',
    status: 'approved',
    inputs: [{ name: 'memberNumber', valueType: 'string', required: true }],
    outputs: [
      { name: 'address', valueType: 'string', required: true },
      { name: 'verifiedAt', valueType: 'date', required: true },
    ],
    steps: [
      {
        stepId: 'navigate-to-login',
        action: { actionType: 'navigate', url: 'http://127.0.0.1:4000/login' },
      },
      {
        stepId: 'fill-member-number',
        action: {
          actionType: 'fill',
          target: [{ strategy: 'role', role: 'textbox', accessibleName: 'Member Number' }],
          value: '{{memberNumber}}',
        },
      },
    ],
    checkpoints: [],
    extractions: [],
    businessOutcomes: [],
  },
  {
    capabilityId: 'list_recent_transactions',
    name: 'list_recent_transactions',
    version: 2,
    goal: 'Last N postings on a given share',
    status: 'approved',
    tenantOverride: true,
    inputs: [
      { name: 'memberNumber', valueType: 'string', required: true },
      { name: 'shareId', valueType: 'string', required: true },
      { name: 'limit', valueType: 'number', required: false },
    ],
    outputs: [{ name: 'transactions', valueType: 'string', required: true }],
    steps: [
      {
        stepId: 'navigate-to-login',
        action: { actionType: 'navigate', url: 'http://127.0.0.1:4000/login' },
      },
      {
        stepId: 'open-transactions',
        action: { actionType: 'click', target: [{ strategy: 'text', text: 'Transaction History' }] },
      },
    ],
    checkpoints: [],
    extractions: [],
    businessOutcomes: [],
  },
  {
    capabilityId: 'open_savings_subaccount',
    name: 'open_savings_subaccount',
    version: 1,
    goal: 'Create a new share and reach the confirmation screen',
    status: 'draft',
    irreversible: true,
    inputs: [
      { name: 'memberNumber', valueType: 'string', required: true },
      { name: 'shareType', valueType: 'string', required: true },
      { name: 'initialDeposit', valueType: 'number', required: true },
    ],
    outputs: [{ name: 'newShareId', valueType: 'string', required: true }],
    steps: [
      {
        stepId: 'navigate-to-login',
        action: { actionType: 'navigate', url: 'http://127.0.0.1:4000/login' },
      },
      {
        stepId: 'open-subaccount-form',
        action: { actionType: 'click', target: [{ strategy: 'text', text: 'Open Sub-Account' }] },
      },
    ],
    checkpoints: [],
    extractions: [],
    businessOutcomes: [],
  },
];

export const runs: RunLog[] = [
  {
    runId: 'rpl_01K7M2',
    mode: 'replay',
    capabilityId: 'read_member_savings_balance',
    capabilityVersion: 3,
    artifactSha: '4f1c…9ab2',
    tenant: 'riverbend-cu',
    caller: 'agent:servicing-copilot',
    inputs: { memberNumber: '<redacted>' },
    startedAt: '2026-09-16T09:10:00Z',
    completedAt: '2026-09-16T09:10:03.912Z',
    modelCalls: 0,
    evidencePath: 'runs/rpl_01K7M2/',
    timeline: [
      {
        stepId: 'navigate',
        title: 'navigate → /servicing/default.aspx',
        detail: 'frameset settled',
        durationMs: 412,
        state: 'passed',
      },
      {
        stepId: 'assert-menu',
        title: 'assert → servicing menu present',
        detail: 'session still authenticated',
        durationMs: 96,
        state: 'passed',
      },
      {
        stepId: 'fill-member-number',
        title: 'fill → Member Number',
        detail: 'a11y name match',
        durationMs: 128,
        state: 'passed',
        resolvedByIndex: 0,
      },
      {
        stepId: 'click-search',
        title: 'click → Search',
        detail: 'postback settled',
        durationMs: 1204,
        state: 'passed',
        resolvedByIndex: 0,
      },
      {
        stepId: 'assert-rows',
        title: 'assert → result grid rows ≥ 1',
        detail: '1 row — no branch taken',
        durationMs: 88,
        state: 'passed',
      },
      {
        stepId: 'click-member-row',
        title: 'click → member row 1',
        detail: 'row link by a11y name',
        durationMs: 1340,
        state: 'passed',
        resolvedByIndex: 0,
      },
      {
        stepId: 'extract',
        title: 'extract → savingsBalance, asOf',
        detail: 'typed and masked at boundary',
        durationMs: 156,
        state: 'passed',
      },
      {
        stepId: 'checkpoint',
        title: 'checkpoint → all_of passed',
        detail: '3 of 3 asserts true',
        durationMs: 88,
        state: 'passed',
      },
    ],
    outcome: {
      classification: 'success',
      outputs: {
        savingsBalance: 4182.9,
        shareAccountNumber: '****1189',
        asOf: '2026-09-12T14:22:00Z',
      },
    },
  },
  {
    runId: 'rpl_01K8Q9',
    mode: 'replay',
    capabilityId: 'read_member_savings_balance',
    capabilityVersion: 3,
    artifactSha: '4f1c…9ab2',
    tenant: 'riverbend-cu',
    caller: 'agent:servicing-copilot',
    inputs: { memberNumber: '<redacted>' },
    startedAt: '2026-09-16T11:04:00Z',
    completedAt: '2026-09-16T11:04:18Z',
    modelCalls: 0,
    interventionId: 'itv_4471',
    evidencePath: 'runs/rpl_01K8Q9/',
    failureEvidence: {
      atStepId: 'click-member-row',
      expected: 'text "SHARE SUMMARY" in frame[main]',
      observed: 'text "Session has expired" · frame src /login.aspx',
    },
    timeline: [
      {
        stepId: 'navigate',
        title: 'navigate → /servicing/default.aspx',
        detail: 'frameset settled',
        durationMs: 440,
        state: 'passed',
      },
      {
        stepId: 'assert-menu',
        title: 'assert → servicing menu present',
        detail: 'passed',
        durationMs: 102,
        state: 'passed',
      },
      {
        stepId: 'fill-member-number',
        title: 'fill → Member Number',
        detail: 'a11y name match',
        durationMs: 131,
        state: 'passed',
        resolvedByIndex: 0,
      },
      {
        stepId: 'click-search',
        title: 'click → Search',
        detail: 'retried once — postback slow (6.2s)',
        durationMs: 8410,
        state: 'degraded',
        resolvedByIndex: 1,
      },
      {
        stepId: 'assert-rows',
        title: 'assert → result grid rows ≥ 1',
        detail: '1 row',
        durationMs: 94,
        state: 'passed',
      },
      {
        stepId: 'click-member-row',
        title: 'click → member row 1',
        detail: 'halted — content frame replaced by /login.aspx; undeclared state',
        durationMs: 8820,
        state: 'failed',
      },
      {
        stepId: 'extract',
        title: 'extract → savingsBalance, asOf',
        detail: 'not reached',
        state: 'not_reached',
      },
      {
        stepId: 'checkpoint',
        title: 'checkpoint → all_of',
        detail: 'not reached',
        state: 'not_reached',
      },
    ],
    outcome: {
      classification: 'failed',
      failureCode: 'session_expired',
      message:
        'Session expired mid-flow and the login frame replaced the content frame. Not a declared outcome, so replay halted rather than clicking blindly into an authentication screen. An intervention was raised automatically.',
      failedAtStepId: 'click-member-row',
      interventionRaised: true,
    },
  },
  {
    runId: 'rpl_01K9T4',
    mode: 'replay',
    capabilityId: 'read_member_savings_balance',
    capabilityVersion: 3,
    artifactSha: '4f1c…9ab2',
    tenant: 'riverbend-cu',
    caller: 'agent:servicing-copilot',
    inputs: { memberNumber: '<redacted>' },
    startedAt: '2026-09-16T13:22:00Z',
    completedAt: '2026-09-16T13:22:04.4Z',
    modelCalls: 0,
    evidencePath: 'runs/rpl_01K9T4/',
    timeline: [
      {
        stepId: 'navigate',
        title: 'navigate → /servicing/default.aspx',
        detail: 'frameset settled',
        durationMs: 402,
        state: 'passed',
      },
      {
        stepId: 'fill-member-number',
        title: 'fill → Member Number',
        detail: 'a11y name match',
        durationMs: 120,
        state: 'passed',
        resolvedByIndex: 0,
      },
      {
        stepId: 'click-search',
        title: 'click → Search',
        detail: 'postback settled',
        durationMs: 1180,
        state: 'passed',
        resolvedByIndex: 0,
      },
      {
        stepId: 'assert-rows',
        title: 'assert → result grid rows ≥ 1',
        detail: '0 rows — "No records" banner matched',
        durationMs: 92,
        state: 'passed',
      },
    ],
    outcome: {
      classification: 'business_outcome',
      code: 'member_not_found',
      message: 'No member matched the supplied number',
    },
  },
  {
    runId: 'rpl_01KB18',
    mode: 'replay',
    capabilityId: 'read_member_savings_balance',
    capabilityVersion: 3,
    artifactSha: '4f1c…9ab2',
    tenant: 'riverbend-cu',
    caller: 'agent:servicing-copilot',
    inputs: { memberNumber: '<redacted>' },
    startedAt: '2026-09-16T15:47:00Z',
    completedAt: '2026-09-16T15:47:12.6Z',
    modelCalls: 0,
    evidencePath: 'runs/rpl_01KB18/',
    timeline: [
      {
        stepId: 'navigate',
        title: 'navigate → /servicing/default.aspx',
        detail: 'maintenance interstitial dismissed',
        durationMs: 3610,
        state: 'degraded',
      },
      {
        stepId: 'fill-member-number',
        title: 'fill → Member Number',
        detail: 'label-anchored table walk',
        durationMs: 260,
        state: 'degraded',
        resolvedByIndex: 1,
      },
      {
        stepId: 'click-search',
        title: 'click → Search',
        detail: 'postback settled',
        durationMs: 1290,
        state: 'passed',
        resolvedByIndex: 0,
      },
      {
        stepId: 'extract',
        title: 'extract → savingsBalance, asOf',
        detail: 'typed and masked at boundary',
        durationMs: 164,
        state: 'passed',
      },
      {
        stepId: 'checkpoint',
        title: 'checkpoint → all_of passed',
        detail: '3 of 3 asserts true',
        durationMs: 90,
        state: 'passed',
      },
    ],
    outcome: {
      classification: 'recovered',
      recoveredFrom: 'locator_not_found',
      attempts: 2,
      outputs: {
        savingsBalance: 4182.9,
        shareAccountNumber: '****1189',
        asOf: '2026-09-12T14:22:00Z',
      },
    },
  },
];
